# Don't print a new line at the start of the prompt
# add_newline = false

[git_status]
conflicted = "ğŸ³"
ahead = "${count}"
# ahead = "â¡ï¸ ${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "$â¬…ï¸ ${count}"
modified = "ğŸ“"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
staged = '[++\($count\)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_branch]
symbol = "ğŸŒ± "
# truncation_length = 4
# truncation_symbol = ""
