# Don't print a new line at the start of the prompt
# add_newline = false

# [battery]
# full_symbol = "ğŸ”‹"
# charging_symbol = "âš¡ï¸"
# discharging_symbol = "ğŸ’€"

# [memory_usage]
# show_percentage = true
# show_swap = true
# threshold = 10
# icon = " M "
# style = "bold dimmed green"
# disabled = false

[env_var]
format = "with [$env_value]($style) "
style = "white dimmed"
symbol = "ğŸš "
variable = "SHELL"


[git_status]
conflicted = "ğŸ¥·"
ahead = "ğŸ¹${ahead_count}"
# ahead = "$count"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "ğŸ”™ ${behind_count}"
modified = "âœï¸ "
untracked = "â“"
stashed = "ğŸ—‘ï¸ "
staged = '${count}â•'
renamed = "ğŸ‘…"
deleted = "â›”"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_branch]
symbol = "ğŸŒ± "
# truncation_length = 4
# truncation_symbol = ""

[jobs]
symbol = "ğŸ”¨ "
